# Define the goal
nav_msgs/Path path
bool[] look_forward
bool go_to_every_target
bool do_avoidance
int32 max_times_backwards
---
# Define the result
---
# Define a feedback message
int32 targets_left
float64 distance_to_next_target